### ISSUE TITLE
how to pack encrypted  field35(track2) with jpos

### ISSUE THREAD

**Issue by peijie-sh** [jpos/jPOS#122]
My track2 data has been encrypted (like this: 6225551353908773=1903669D5A90717EB7B0).
I try to use  `isoMsg.pack()` to pack the msg.
However,the msg i send out is incorrect but without any exception.

here is part of my code to definate `ISOFieldPackager`.
```
/*035*/ new IFB_LLNUM(37, "Track 2 data", false),
/*036*/ new IFB_LLLNUM(104, "Track 3 data", false),
```
I also tried `IFB_LLCHAR` and `IFB_LLBINARY`.
I have no idea about which kind of class should i use.
The jpos version in my code is 2.0.4.

**Comment by vsalaman** [comment]
You should use what your other end is expecting. If I had to venture I'd use IFA_LLCHAR.

**Comment by peijie-sh** [comment]
After packed, the length should be one byte in bcd value, and the data should be 19 bytes in hex (0-9 A-F) value.
Can you give me some suggestion?

**Comment by vsalaman** [comment]
You might need to write your own ISOFieldPackager...

**Comment by peijie-sh** [comment]
okay,thank you for your answer ^_^

**Comment by ar** [comment]
I don't think this is a jPOS issue. This is a jPOS question, you should use the mailing list, StackOverflow, Slack, IRC or smoke signals, but not the issue tracker.
