### ISSUE TITLE
how to use client server simulator using maven dependency in JPOS

### ISSUE THREAD

**Issue by nmarunbalaji** [jpos/jPOS#148]
Could anyone guide me how to configure client server simulator in jPOS.
our requirement is to simulate a ATM transaction message and then we need to parse it using ISO message parser.
Thanks in advance
Arun Balaji NM

**Comment by ar** [comment]
Please check http://jpos.org/blog/2017/11/asking-a-smart-question/

Do not open issues like this or we'll have to ban you.
