### ISSUE TITLE
No IFE_LLLNUM

### ISSUE THREAD

**Issue by MouslihAbdelhakim** [jpos/jPOS#151]
Hello,

I just noticed that there is no IFE_LLLNUM ISOStringFieldPackager, is there a reason for this ? should we implement it ?

Kind regards.

**Comment by ar** [comment]
It seems we didn't face any endpoint requiring it, but yes, IFE_LLLNUM should be available.
Do you want to send a PR? (I can implement it if you want, no problem).

**Comment by MouslihAbdelhakim** [comment]
@ar Thank you for the swift reply, i'll implement it with any other missing ISOStringFieldPackager and open a PR (:

**Comment by mchhil** [comment]
When builds fail, the red cross has a link which is not traversable, is there a configuration setting that needs to be fixed  somewhere?
The link content is :
https://travis-ci.org/MouslihAbdelhakim/jPOS/builds/339536290?utm_source=github_status&utm_medium=notification

**Comment by ar** [comment]
@mchhil Not sure I know how to fix that, will check, perhaps it has to do with Travis admin karma.
