### ISSUE TITLE
Manifest issue in jpos-2.1.x.jar

### ISSUE THREAD

**Issue by narwajea** [jpos/jPOS#169]
When running a Spring Boot app locally that use jPOS 2.1.0 or 2.1.1, I encounter a warning right at the start of the app. It looks like a problem in the MANIFEST.MF file:

```
Class-Path: lib/jdom2-2.0.6.jar lib/jdbm-1.0.jar lib/je-7.0.6.jar lib/
 commons-cli-1.3.1.jar lib/jline-3.2.0.jar lib/bsh-2.0b6.jar lib/javat
 uples-1.2.jar lib/org.osgi.core-6.0.0.jar lib/bcprov-jdk15on-1.56.jar
  lib/bcpg-jdk15on-1.56.jar lib/sshd-core-1.3.0.jar lib/slf4j-api-1.7.
 22.jar lib/javassist-3.21.0-GA.jar lib/HdrHistogram-2.1.9.jar
```

Dependency used:

```
            <dependency>
                <groupId>org.jpos</groupId>
                <artifactId>jpos</artifactId>
                <version>2.1.0</version>
            </dependency>
```

Warning message:

```
The Class-Path manifest attribute in
C:\Users\username\.m2\repository\org\jpos\jpos\2.1.0\jpos-2.1.0.jar referenced one or more files that do not exist: 
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/jdom2-2.0.6.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/jdbm-1.0.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/je-7.0.6.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/commons-cli-1.3.1.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/jline-3.2.0.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/bsh-2.0b6.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/javatuples-1.2.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/org.osgi.core-6.0.0.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/bcprov-jdk15on-1.56.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/bcpg-jdk15on-1.56.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/sshd-core-1.3.0.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/slf4j-api-1.7.22.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/javassist-3.21.0-GA.jar,
file:/C:/Users/username/.m2/repository/org/jpos/jpos/2.1.0/lib/HdrHistogram-2.1.9.jar
```

Issue linked to this one: https://github.com/spring-projects/spring-boot/issues/11057

**Comment by ar** [comment]
jPOS needs those libraries so you can run `java -jar jpos.jar` - I don't think this is a jPOS issues.

**Comment by chhil** [comment]
Its trying to retrieve jars from a local repository , possibly because its not packaged in the distribution you are running. How are you building your distribution ?

**Comment by narwajea** [comment]
Let me explain what happens exactly.

The jpos jar references several libraries needed to run it as explained by @ar. That means it is not only a library jar (used as a dependency in my Spring Boot app), but also an executable jar.

I package my application with Maven (as you might guess from the dependency above). I run my application locally in my IDE (Eclipse) with the Spring IDE plugin. Spring checks the MANIFEST of each dependency, and consequently checks if there are some jar files in a /lib folder next to jpos-2.1.0.jar. Of course there isn't, because this libraries reside in their own folder, e.g. `C:\Users\username\.m2\repository\org\jdom\jdom2\2.0.6` for jdom2-2.0.6.jar.

Then Spring alerts about the missing files, but the app works fine though, because it is packaged & run from Maven dependencies. So this warning is just informative.

First, why is jpos jar an executable jar ?

Second, this standalone jar file should not reference other libs in the Class-Path entry of its MANIFEST  file, otherwise it should have been packaged as an uber jar containing those libs. That's the way apps are packaged nowadays.

**Comment by chhil** [comment]
Traditionally (ant), all the jars are packaged put in the lib folder and speaking for myself here we run the executable jar using a windows service or a shell script. Gradle which is used today probably does the same thing today. I will let the Alejandro (architect) of the jpos answer your queries.

**Comment by ar** [comment]
> That means it is not only a library jar (used as a dependency in my Spring Boot app), but also an executable jar.
Exactly. jPOS is a library and it embeds Q2 which is a Framework. The manifest comes very handy when running Q2, used by most jPOS applications. But I see your point, we don't necessarily need to place that manifest in the jpos jar, it's can go in the jPOS application built by the jPOS template.

Being able to "run" a jPOS application in the way we currently do inside the development build comes very handy, but we don't necessarily have to publish it at release time. I'll take a look at that, specially checking we don't break any OSGi related support.

As a temporary work around, you can remove line 90 in `jpos/build.gradle`, call `gradle install` and pick it from maven local, just to verify this fixes your problem.

Sounds reasonable @narwajea ?

**Comment by narwajea** [comment]
> we don't necessarily need to place that manifest in the jpos jar

Exactly.

> I'll take a look at that, specially checking we don't break any OSGi related support.

Thank you.

> you can remove line 90

And line 94 ?

> Sounds reasonable @narwajea ?

Sounds good to me, thank you. Please let me know when you release a new version without the Class-Path entry.

**Comment by ar** [comment]
> And line 94 ?
Sure, actually line 94 is the only one that matters, but 90 should be taken away too just because it would become obsolete.

> Please let me know when you release a new version
You'll see this issue closed.

**Comment by ar** [comment]
@narwajea - this issue has been fixed in 2.1.2-SNAPSHOT and a nightly build has been forced.

Can you give it a try and confirm it works for you? (please note you need to add http://jpos.org/maven as a repo)

**Comment by ar** [comment]
Thank you for the confirmation. Will close the issue. We expect to release `2.1.2` soon to Maven Central.

**Comment by ar** [comment]
We are very close to delivery, hopefully by mid-July.
