### ISSUE TITLE
Subfields is not a fixed problem

### ISSUE THREAD

**Issue by leleZeng** [jpos/jPOS#179]
Hello !

I'm sorry to disturb your time,and I hope you can help me solve some of the problems.

When the number of sub field of a data element is not fixed, I will write all the sub field that may exist, but 

it is found that if the number of sub field in this domain and the number of numbers written in the 

configuration file are not at the same time, it will throw an exception, and if the length of the sub field 

data is inconsistent, there will be an exception.

`<isofieldpackager
      id="61"
      length="999"
      name=""
      class="org.jpos.iso.IFE_LLLCHAR" packager="org.jpos.iso.packager.ISO87BPackager">
	       <isofield name="" length="1" class="org.jpos.iso.IF_CHAR" id="0"/>
	       <isofield name="" length="1" class="org.jpos.iso.IF_CHAR" id="1"/>
	       <isofield name="" length="5" class="org.jpos.iso.IF_CHAR" id="2"/>
  </isofieldpackager>`

The subfields of the message is not fixed, and there will be up to three subfield. If there are no three sub domains at runtime, an exception will be thrown.

The length of the third subfields is not fixed, and the data length is up to 5. If the message is 3, it will throw an exception.

Best Regards,

**Comment by ar** [comment]
If the system is not properly configure, it's quite reasonable it throws an exception. This is not an issue.

**Comment by leleZeng** [comment]
I see what you mean. How do I configure it to support unfixed subfields numbers and subfields data length?

**Comment by ar** [comment]
This is not something to be handled as an issue - see http://jpos.org/resources and ask in jpos-users mailing list.
