### ISSUE TITLE
Data corruption for non-ASCII characters

### ISSUE THREAD

**Issue by afterwhy** [jpos/jPOS#180]
In `ISOStringFieldPackager.unpack()` unpacked string is created via `Literal.uninterpret()` method with 
`new String(rawData, offset, length, ISOUtil.CHARSET)`, i.e. using ISO_8859_1 charset.

Right after that ISOComponent value is setted via `setValue()` method and in case if component is ISOMsg the code is following `((String) obj).getBytes()`, i.е. with default (UTF-8) encoding.

At this point if data contained any non-ASCII characters it became broken.

I suggest to specify encoding in `setValue()` method to prevent such behaviour.
I attached simple [patch](https://github.com/jpos/jPOS/files/2242208/0001-Prevent-data-corruption-for-non-ASCII-characters.txt) to illustrate the proposed change

**Comment by ar** [comment]
Thank you for the patch. Applied in 41cbd7a5b.
