### ISSUE TITLE
Optionally shutdown Q2 on configuration error

### ISSUE THREAD

**Issue by ar** [jpos/jPOS#191]
When there's a configuration error, Q2 renames the QBean descriptor to `.BAD` or `.DUP` and raises a `ConfigurationException`. In some scenarios, it is desirable to actually exit Q2 (so that the problem can be eagerly detected).

This should be an option (either configuration property or Q2 start-up flag.

**Comment by alcarraz** [comment]
What if, while we work on a more sophisticated solution, we just add a strategy for handling the different exceptions/errors?

One could plug a strategy and the default one would do what it currently does. So we give total freedom to developers.

We can later implement other behaviors, or even as a strategy, a `fail-on-errors` (or the like) flag could activate a specific strategy, if we want to implement it. But then someone could choose to implement a strategy that only quits on errors, or only on dups, or even on a condition of the filename.

This comment was fired by [a discussion on slack](https://jpos.slack.com/archives/CHAB8RFKK/p1700607902483779), link valid for 90 days.

**Comment by alcarraz** [comment]
Also, this issue is quite related to #553

**Comment by ar** [comment]
> What if, while we work on a more sophisticated solution, we just add a strategy for handling the different exceptions/errors?

I don't think we want to have a thousand ways to achieve a simple thing such as aborting on failing QBeans. The `--exit-on-failed-deploy=startup|always` is all we need. I'll close this issue and we can continue in #553.
