### ISSUE TITLE
IFEP_LLLBINARY field max length cannot be initialized as with other packagers

### ISSUE THREAD

**Issue by gitmik** [jpos/jPOS#201]
IFEP_LLLBINARY field packager does not support length and description initialization via constructor as in other packagers, in example IFE_LLLEBINARY. To use IFE_LLLBINARY it needs explicit len initialization with a setter call.

**Comment by ar** [comment]
Care to send a PR @gitmik ?

**Comment by gitmik** [comment]
Sorry, I have it locally, its a small change, willa push in the morning.

**Comment by gitmik** [comment]
PR already merged with #202 
closing this one.
