### ISSUE TITLE
Concurrent hit make the server not accepting connection

### ISSUE THREAD

**Issue by Darkxylitol** [jpos/jPOS#234]
I am use v2.1.3 to do some TPS benchmark, with around 10 simultanously continuous hit. After several point of time, there's error on client side said: unable to connect, meanwhile the server socket remain listening.

**Comment by alcarraz** [comment]
There are many possible reasons for that, and heavily depends on your code+deploy, can you share reproducible test case?

Until you can confirm it is a bug in jpos and not in your code I suggest you to use the [jpos users list](http://www.jpos.org/resources) to address your issue.

But please always share reproducible code if you want to report a bug or issue.

**Comment by Darkxylitol** [comment]
I post here, because i cant see any clue outside there, please find below:

[+] create atleast 3 channel 
[+] hit those 3 simultaneously with either jmeter (10 thread, 10000 loop) or org.jpos.iso.BaseChannel continuously 
[+] you will get an "unable to connect" once server processing the heavy request.

No log inside the server side, only the client cant connect.

[jmeter.log.txt](https://github.com/jpos/jPOS/files/3406770/jmeter.log.txt)
[client.log.txt](https://github.com/jpos/jPOS/files/3406777/client.log.txt)

**Comment by alcarraz** [comment]
if we don't know what you are doing on the server, how can we know why the server is not accepting connections?

Again share reproducible code please.
