### ISSUE TITLE
100% CPU usage in GenericTaggedFieldsPackager

### ISSUE THREAD

**Issue by demsey** [jpos/jPOS#248]
Although commit 686be85 solves the problem of unsorted subtags, but **it introduces a new problem associated with an infinite loop** _(100% cpu)_ when the message contains a new _(not yet defined)_ subtag _(then the variable `consumed` never increases)_.

Proposed solution _(update `GenericTaggedFieldsPackager.unpack`)_:
```java
            if (logger != null)  // save a few CPU cycle if no logger available
                evt.addMessage(ISOUtil.hexString(b));

            int consumed = 0;
            TagMap tm = unpackTLV(b);
            for (Tag tag : tm.values()) {
                int i =  tagMapper.getFieldNumberForTag(fieldId, tag.getTagId());
                ISOComponent c = fld[i].createComponent(i);
                byte[] bb = tag.getTLV().getBytes(ISOUtil.CHARSET);
                int unpacked = fld[i].unpack(c, bb, 0);
                consumed = consumed + unpacked;
                m.set(c);
            }
            if (b.length != consumed) {
                evt.addMessage(
                        "WARNING: unpack len=" + b.length + " consumed=" + consumed);
            }
            return consumed;
```
It require new classes `org.jpos.tlv.TagMap`, `org.jpos.tlv.Tag` to handle `String` encoded TLV data. _(Better name suggestions are welcome)_. They are similar to `org.jpos.tlv.TLVList`, `org.jpos.tlv.TLVMsg` but they handle `String` data not byte arrays and each tag can occur only once.
Example in branch https://github.com/demsey/jPOS/commits/tlvfield commit demsey@7d1dbe463

**Comment by ar** [comment]
Do you have this solution running? Can you send a PR?

**Comment by demsey** [comment]
Yes, this solution has been in production since 2016, but we have recently withdrawn to the stock 686be85 commit.
I can clean up the https://github.com/demsey/jPOS/commits/tlvfield branch and make PR.

Any suggestions for class names: `org.jpos.tlv.TagMap`, `org.jpos.tlv.Tag` ?
I think that package `org.jpos.tlv` is ok, but I don't like the class names

**Comment by ar** [comment]
`TagMap` and `Tag` look OK to me, we can always change it later and break some code :) :)

**Comment by demsey** [comment]
@ar Could you see the updated commit demsey@7bccd24c3?
Unfortunately, I already know why it is still not ready for the public repository - **My solution breaks the possibility of using different TLV sizes** _(tag, length)_ in the packager configuration. It only supports fixed `T=2`, `L=3` _(which suits me)_

To solve this, more radical action is needed. Introduction of the `tagSize` and `lenSize` attributes at the `GenericTaggedFieldsPackager` level and abandoning the use of TLV suited packagers in `GenericTaggedFieldsPackager` such as `org.jpos.iso.IFA_TTLLCHAR`, `org.jpos.iso.IFA_TTLLBINARY` in favor of generic `org.jpos.iso.IFA_CHAR`, `org.jpos.iso.IFA_BINARY`, `org.jpos.iso.IFA_BINARY`,

Instead actual
```xml
  <isofieldpackager
      id="48"
      length="999"
      name="Additional Data Private Use"
      class="org.jpos.iso.IFA_LLLCHAR"
      tagMapper="org.jpos.iso.packager.TTDecimalTagMapper"
      packager="org.jpos.iso.packager.GenericTaggedFieldsPackager">
      <isofield
          id="1"
          length="29"
          name="Some ascii value 1"
          class="org.jpos.iso.IFA_TTLLCHAR"/>
      <isofield
          id="2"
          length="12"
          name="Some binary value 2"
          class="org.jpos.iso.IFA_TTLLBINARY"/>
      <isofield
          id="3"
          length="8"
          name="Some ascii value 3"
          class="org.jpos.iso.IFA_TTLLCHAR"/>
  </isofieldpackager>
```
we get:
```xml
  <isofieldpackager
      id="48"
      length="999"
      name="Additional Data Private Use"
      class="org.jpos.iso.IFA_LLLCHAR"
      tagMapper="org.jpos.iso.packager.TTDecimalTagMapper"
      tagSize="2", lenSize="2"
      packager="org.jpos.iso.packager.GenericTaggedFieldsPackager">
      <isofield
          id="1"
          length="29"
          name="Some ascii value 1"
          class="org.jpos.iso.IFA_CHAR"/>
      <isofield
          id="2"
          length="12"
          name="Some binary value 2"
          class="org.jpos.iso.IFA_BINARY"/>
      <isofield
          id="3"
          length="8"
          name="Some ascii value 3"
          class="org.jpos.iso.IFA_CHAR"/>
  </isofieldpackager>
```
This description is much more consistent _(does not allow mixing tag types, that are not allowed in TLV datasets)_
Also is possible to introduce `swapTagAndLen="true"` attribute to emulate packagers family like `org.jpos.iso.IFA_LLTTCHAR`

Ultimately, you can get rid of all packagers families like `IFA_TTLLCHAR`, `IFA_TTLLLCHAR`, `IFA_TTTLLLCHAR`, `IFA_LLTTCHAR`, `IFA_LLLTTCHAR` and so on...

**Comment by ar** [comment]
I like where this is heading. The `swapTagAndLen` would be great, I have TLV and LTV custom implementations here and there. Wonder if you want to commit a work-around the 100% CPU usage issue first, until we can work on this further.
