### ISSUE TITLE
FSDMsg copy doesn't support a default value

### ISSUE THREAD

**Issue by alwyn** [jpos/jPOS#260]
FSDMsg copy doesn't support a default value in case the source object doesn't contain the field.

**Comment by ar** [comment]
You mean https://github.com/jpos/jPOS/blob/master/jpos/src/main/java/org/jpos/util/FSDMsg.java#L553-L555 ?

We can add a `copy (String fieldName, FSDMsg msg, String defValue)`.

Is that what you need?

**Comment by alwyn** [comment]
I have created a PR with the change.

**Comment by ar** [comment]
Excellent! Merged.
