### ISSUE TITLE
Q2 log shows deploy file renamed to bad but its not actually renamed.

### ISSUE THREAD

**Issue by chhil** [jpos/jPOS#289]
https://github.com/jpos/jPOS/blob/master/jpos/src/main/java/org/jpos/q2/Q2.java#L932-L939

The java File.renameTo returns a boolean, and we should use that flag and log the appropriate error if it was renamed or an attempt to rename failed.

**Comment by ar** [comment]
Fixed in https://github.com/jpos/jPOS/pull/290
