### ISSUE TITLE
Issue with BERTLVPackager

### ISSUE THREAD

**Issue by karlmuscat-dpg** [jpos/jPOS#314]
For tags are have `PACKED_NUMERIC`, `PACKED_NUMERIC_DATE_YYMMDD` and `PACKED_NUMERIC_TIME_HHMMSS` formats, the `BERTLVPackager` `unpackValue` method is dropping any leading 0. 

This is breaking the date and time patterns. Eg: 21530 is not a valid HHMMSS.

What is the reason that this truncation is happening?

**Comment by ar** [comment]
Can you provide a Unit test? (see issue #315 for a recent example, feel free to add tests to that class)

**Comment by karlmuscat-dpg** [comment]
@ar added PR #317

**Comment by karlmuscat-dpg** [comment]
Added more tests that highlight the dropping of the leading 0.

For certain elements, such as country or currency codes like as `5F2A`, dropping this zero does not change the meaning of the value.

However for other elements, such as transaction amounts like `9F02`, dropping the leading zero, changes the actual value from `000000000033` to `00000000033`.

The relevant code seems to be `if` condition (lines 409-411) within the `BERTLVPackager.unpackValue` class:

```

**Comment by karlmuscat-dpg** [comment]
Hi @ar. I noticed that you reverted the change for `PACKED_NUMERIC`. As I had mentioned earlier, there are cases. like `9F02` where dropping a zero, changes the meaning of the value. Can you explain why you consider this as correct behaviour to have> Thanks

**Comment by ar** [comment]
I reverted because the change broke `EMVTagSequenceTest.testPacking()` gives:

   `Unpack error ==> expected: <840> but was: <0840>`

I believe the test case is correct.

**Comment by karlmuscat** [comment]
I understand why the revert. What I don't understand is the decision to truncate the first zero only. Why only the first 0? As for the failing test case, if the value of the tag value is really `0840` why is the test expecting `840`? I don't think this data manipulation is correct.

**Comment by karlmuscat-dpg** [comment]
I understand why the revert. What I don't understand is the decision to truncate the first zero only. Why only the first 0? As for the failing test case, if the value of the tag value is really `0840` why is the test expecting `840`? I don't think this data manipulation is correct.

**Comment by ar** [comment]
> What I don't understand is the decision to truncate the first zero only. Why only the first 0?

You just need one 0 to pad an odd-length number, such as the currency code 840. A number such as '0001' would be coded as just one byte '01', and we would just swallow the first '0' to return '1'.

**Comment by ar** [comment]
Sorry I missed your second comment:

> However, for other tags, like 9F02, the length is expected to be 12. So the data manipulation for PACKED_NUMERIC is breaking that contract (since it returns a 11 digit number).

That's a good point. Will check that.
