### ISSUE TITLE
Transactionmanager in-transit printing representation is different in 2 places

### ISSUE THREAD

**Issue by chhil** [jpos/jPOS#318]
Is the difference one as a number and the other as a ratio intentional ?

https://github.com/jpos/jPOS/blob/c236fd1b86eddc27a3e8aa723dfd30c8b57fba25/jpos/src/main/java/org/jpos/transaction/TransactionManager.java#L388
 ```
String.format (" in-transit=%d, head=%d, tail=%d, paused=%d, outstanding=%d, active-sessions=%d/%d, %s, elapsed=%dms",
                            getInTransit(), head, tail, pausedCounter.get(), getOutstandingTransactions(),
                            getActiveSessions(), maxSessions,
                            tps.toString(), prof != null ? prof.getElapsedInMillis() : -1
                        )
```

https://github.com/jpos/jPOS/blob/c236fd1b86eddc27a3e8aa723dfd30c8b57fba25/jpos/src/main/java/org/jpos/transaction/TransactionManager.java#L507
     
  ```
 ps.printf ("%sin-transit=%d/%d, head=%d, tail=%d, paused=%d, outstanding=%d, active-sessions=%d/%d%s%n",
          indent,
          getActiveTransactions(), getInTransit(), head, tail, pausedCounter.get(), getOutstandingTransactions(),
          getActiveSessions(), maxSessions,
          (tps != null ? ", " + tps.toString() : "")
        );

```

**Comment by ar** [comment]
> Is the difference one as a number and the other as a ratio intentional ?
Nah... probably missing ratio in one of the calls. I'll move that to a helper method. Thanks for raising this issue.
