### ISSUE TITLE
TransactionManager does not call selector someTime

### ISSUE THREAD

**Issue by samansalehi** [jpos/jPOS#400]
i have been useing  jpos version 2.1.0 recently in my project. sometime transaction manager get the message and log it in log file but do not selected  by our group selector so after a while transaction reversed by host but, some time it work correctly with the same message format. it cause to increase the number of transaction timeout. 
i choose the session= 2 and maxSession=128

**Comment by ar** [comment]
This issue doesn't have enough information to be researched.  Perhaps you want to share some logs in the jpos-users mailing list (see http://jpos.org/resources).
