### ISSUE TITLE
Jpos hangs on response 204 

### ISSUE THREAD

**Issue by mpp-jamesl** [jpos/jPOS#405]
Jpos server hangs on HttpResponse 204 

When sending a request to an API which returns a 204 on success.

If you need to have the responseBodyOnError = true 
and the API sends back a 204 on success the Jpos server just hangs. The issue is around the following code within the HttpQuery class 

`
boolean includeResponse= (sc == HttpStatus.SC_CREATED) || (sc == HttpStatus.SC_OK) || responseOnError;
                if (includeResponse) {
                    try {
                        ctx.put (responseName, EntityUtils.toString(result.getEntity()));
                    } catch (IOException e) {
                        ctx.log (e);
                    }
                }
`

The actual problem is in this line 
`ctx.put (responseName, EntityUtils.toString(result.getEntity()));`

It is because the EntityUtils is attempting to convert the result.getEntity into an entity to assign as the value for the response name in the context map. 

This causes a hang because the response does not have a body given the 204. 

There should be null safety checks here and if the result.getEntity is null then assign the status value (sc) to the context instead.

**Comment by ar** [comment]
This doesn't seem to be a jPOS issue. Looks like the right project to report this issue is jPOS-EE.

**Comment by mpp-jamesl** [comment]
Hey many thanks for that I'll open the issue there, I have cloned the project and if it's ok with you guys I can make the change and push it onto a branch and raise a pull request or just raise the issue and leave it to your triage process to handle it.

**Comment by ar** [comment]
Sure, go ahead!
