### ISSUE TITLE
How to set header when using base24 packager?

### ISSUE THREAD

**Issue by vinamra28** [jpos/jPOS#477]
Hi folks, can you please guide me how can I set the header of the ISO message using Base24 packager or any packager?
My base24 header looks somewhat like
```
ISO8583 message
    BASE24 ISO Header
    Start of Message        : ISO
    Product Indicator       : 00 - Base
    Release Number          : 16
    Msg Status|Fld in Error : 000
    Originator              : 0 - (not set)
    Responder               : 0 - (not set)
```

@jameshilliard @demsey @ar @alwyn could you please help me here?

I can see there is a class as BaseHeader but I can't find any proper documentation for it. Below is the implementation I was able to try 
```java
ISOHeader isoHeader = new BaseHeader();
isoHeader.setSource("6");
isoHeader.setDestination("0");
```
but I can't find any other exposed method

**Comment by ar** [comment]
This is not a jPOS issue. Please use the mailing list for questions like this.
