### ISSUE TITLE
Allow to load environment properties from multiple files in `Q2` `-E` option.

### ISSUE THREAD

**Issue by alcarraz** [jpos/jPOS#527]
The following code suggests that reading from multiple files for jPOS environment variables is supported:

https://github.com/jpos/jPOS/blob/149800935828a2054c5e74d950d5c6aae7dad29c/jpos/src/main/java/org/jpos/core/Environment.java#L189-L193

However, the `name` variable is loaded from java property `jpos.env` in:

https://github.com/jpos/jPOS/blob/149800935828a2054c5e74d950d5c6aae7dad29c/jpos/src/main/java/org/jpos/core/Environment.java#L64

Which is set by `Q2` in the following way:

https://github.com/jpos/jPOS/blob/149800935828a2054c5e74d950d5c6aae7dad29c/jpos/src/main/java/org/jpos/q2/Q2.java#L761-L763

That makes it impossible to set multiple files through the `-E` option, like in this call:
```shell
java org.jpos.q2.Q2 -Eenv1,env2
```
If this is a bug, I can submit a PR, and add something to the documentation to explicitly document that feature. If the intended behavior is to allow multiple files, only through the `jpos.env` java property, I could submit a PR as well to document that, unless it's intended to be a hidden/experimental feature.

**Comment by ar** [comment]
You need to call `q2 -Eenv1 -Eenv2`

**Comment by alcarraz** [comment]
Ohh, you're right, it says `line.getOptionValues("E")` plural 🤦🏼‍♂️ , sorry for the noise.
