### ISSUE TITLE
Base24Channel is not escaping `ETX` bytes at send time.

### ISSUE THREAD

**Issue by alcarraz** [jpos/jPOS#529]
I was looking at `Base24Channel` class, and just noticed that it isn't escaping `ETX` bytes at send time, it isn't overriding the `send` method. I wonder how, if it is, working when there is an `ETX ` byte present in the data to send.

https://github.com/jpos/jPOS/blob/e586ed62f713e77f19c69dfc34db5cb6afd7cad0/jpos/src/main/java/org/jpos/iso/channel/BASE24Channel.java#L97-L98.

This is not affecting any system that I know of, maybe `Base24` is commonly used with ASCII, or EBCDIC based packagers that do not send this kind of bytes in the payload, or more probably, that I'm just missing something.

**Comment by ar** [comment]
That channel works along an ASCII packager where ETX is an invalid char.

Do you have a specific use case?

**Comment by alcarraz** [comment]
It was pure curiosity, since in the `receive` method it handles `ETX` bytes in the payload, and I was expecting the same in the `send` method. 

I guess this is not a real issue. At least until someone tries to use it with a binary packager and has a hard time figuring out what is going on, which shouldn't happen because this is a legacy control mechanism. 

I should have asked this in another place, such a discussion or over slack.
