### ISSUE TITLE
Any good first issue?

### ISSUE THREAD

**Issue by UnGaucho** [jpos/jPOS#535]
Hey, jpos team.

Is there any good first issue I could take on? What would be a good way to contribute/give back to jpos?

Something like this one https://github.com/jpos/jPOS/issues/410 for example.

**Comment by UnGaucho** [comment]
Maybe this one? https://github.com/jpos/jPOS/issues/508

**Comment by alcarraz** [comment]
Hi @UnGaucho, it's great you want to help, May I suggest closing this, as this isn't an issue, and maybe start a [discussion](https://github.com/jpos/jPOS/discussions) for this?

That said, #510 looks like a low-hanging fruit to begin.

**Comment by UnGaucho** [comment]
Will do thanks!

**Comment by ar** [comment]
Not a good idea to open an issue to ask where to start @UnGaucho. 
We have a mailing list (jpos-users), a Slack group, a Discord, and even a GitChat, and Discussions here.
See http://jpos.org/resources

**Comment by UnGaucho** [comment]
My bad.

Thanks for pointing out the appropriate channels :)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
