### ISSUE TITLE
The trailer is unable to sent from Jpos server to the source.

### ISSUE THREAD

**Issue by Chandhiramouli** [jpos/jPOS#544]
Source sends a trailer (the end of the message) to Jpos, but Jpos is not able to return the trailer to source. 

<img width="706" alt="image" src="https://github.com/jpos/jPOS/assets/68543012/7f5b800c-4c05-407c-91eb-0b5755098a49">

Kindly provide the configuration for sending the trailer from JPOS to the source.

**Comment by ar** [comment]
This is not a jPOS issue.

**Comment by Chandhiramouli** [comment]
Tailer value (end of the transaction) = 03d585 (highlighted yellow color)

![image](https://github.com/jpos/jPOS/assets/68543012/aadfa923-44f2-4eff-86a4-8752eb3949d5)

While sending a response from JPOS, I was not able to pass the trailer.

![image](https://github.com/jpos/jPOS/assets/68543012/e41256a0-d865-4fb4-9d50-03e3392216f1)

In response, I was unable to pass a trailer (03d585) to the source.

**Comment by Chandhiramouli** [comment]
Can you please inform me of any configuration for adding a trailer in the JPOS response?

**Comment by ar** [comment]
Please use the jPOS-users mailing list, or Slack support channel for this kind of questions. This is not a jPOS issue.
See http://jpos.org/resources
