### ISSUE TITLE
The trailer is not added to the JPOS response.

### ISSUE THREAD

**Issue by Chandhiramouli** [jpos/jPOS#545]
****Source sends a trailer (the end of the message) to Jpos, but Jpos is not able to return the trailer to source.**

Kindly refer the supporting images.

**Source sends a 1200 message to jpos. In 1200 request message, trailer was added in jpos code.****

![image](https://github.com/jpos/jPOS/assets/68543012/28779355-66f4-4286-b136-f5759574d45c)

**Wireshark Log for request message (Source to JPOS)**

![image](https://github.com/jpos/jPOS/assets/68543012/960f52d9-5299-4cbe-9865-0aff90009fcb)

**While sending a 1210 message, trailer was not added in Jpos code (Receiving null).**

![image](https://github.com/jpos/jPOS/assets/68543012/482c5b35-bc63-4f94-84c1-569a2d628725)

Wireshark Log for request message (JPOS to Source)

![image](https://github.com/jpos/jPOS/assets/68543012/4a30d11c-2dff-4f47-9fc8-9c7fed87c9fc)

Kindly provide any configuration for adding a trailer in the JPOS response.

**Comment by alcarraz** [comment]
Hi this is not a jPOS issue, if you need help configuring jPOS for handling trailers, please, ask it in proper channels. I believe the most adequate would be the [jPOS users mailing list](http://groups-beta.google.com/group/jpos-users). You can also ask in the [jPOS slack](http://jpos.slack.com/). 

You can see all those resources in http://www.jpos.org/resources.

**Comment by Chandhiramouli** [comment]
Very Thanks for your suggestion.
