### ISSUE TITLE
using BERTLVAsciiHexPackager and AsciiHexInterpreter returns incorrect  uninterpretLength 

### ISSUE THREAD

**Issue by Elias-Terranti** [jpos/jPOS#568]
when using BERTLVAsciiHexPackager  to unpack a tlv , it unpacks the tag correctly but  when the packager calls on getUninterpretLength(len, AsciiHexInterpreter.instance ), the return is always 0, so the value is  an empty array

` my test code:

    public class jposbugtest {

    final String HEX_ASCII = "9f2610e18d2a69a45dd09a9f360401839f3708ab34b0bd";

    @Test
    public void testLenInterpretation() throws ISOException {
        final ISOMsg ICC_DATA = new ISOMsg(55);
        final BERTLVAsciiHexPackager packager = new BERTLVAsciiHexPackager();
        final IFA_LLABINARY fieldPackager = new IFA_LLABINARY();

        packager.setFieldPackager(new org.jpos.iso.ISOFieldPackager[]{fieldPackager});
        ICC_DATA.setPackager(packager);

        ICC_DATA.unpack(HEX_ASCII.getBytes());

        ICC_DATA.getChildren().values().forEach
                (e -> {
                    try {
                        ISOTaggedField field = (ISOTaggedField) e;
                        final byte[] value = (byte[]) field.getValue();
                        System.out.println("tag "+ field.getTag() + " value " + ISOUtil.hexString(value));

                        Assert.assertFalse(Arrays.isNullOrEmpty(value));

                    } catch (ISOException ex) {
                        throw new RuntimeException(ex);
                    }
                });

    }

}`

i tested using  both java 8 and java 17 with same issue

**Comment by ar** [comment]
This TLV payload doesn't seem correct `9f2610e18d2a69a45dd09a9f360401839f3708ab34b0bd`. Tag 9f26 is OK, but tag `ab` is missing data.

```xml
    <tlvlist>
       <tag id='9f26' value='E18D2A69A45DD09A9F360401839F3708' />
    </tlvlist>
```

**Comment by ar** [comment]
The test is not correct. Try this code:

```java
    @Test
    @SuppressWarnings("unchecked")
    public void testLenInterpretation() throws ISOException {
        final String HEX = "9f2610e18d2a69a45dd09a9f360401839f3708"; //     ab34b0bd";

        Logger logger = new Logger();
        logger.addListener(new SimpleLogListener(System.out));

        final ISOMsg ICC_DATA = new ISOMsg(55);
        final BERTLVPackager tlvPackager = new BERTLVBinaryPackager();
        tlvPackager.setLogger(logger, "debug");
        tlvPackager.setFieldPackager(new ISOFieldPackager[]{new IFA_TTLLBINARY()});
        tlvPackager.unpack(ICC_DATA, ISOUtil.hex2byte(HEX));
        ICC_DATA.dump(System.out, "");

        TLVList tlv = new TLVList();
        tlv.unpack(ISOUtil.hex2byte(HEX));
        tlv.dump (System.out, "");

        ICC_DATA.getChildren().values().forEach(e -> {
              try {
                  ISOTaggedField field = (ISOTaggedField) e;
                  final byte[] value = (byte[]) field.getValue();
                  System.out.println("tag "+ field.getTag() + " value " + ISOUtil.hexString(value));
                  assertFalse(Arrays.isNullOrEmpty(value));
              } catch (ISOException ex) {
                  throw new RuntimeException(ex);
              }
        });
    }
```

**Comment by Elias-Terranti** [comment]
hello @ar 

apologies it seams I should have added more details.

the the length represents the decoded value length . 
the program I use to send the ISOMsg  (written in go)  uses a AsciiHex packager. 

so the TLV would be:


| tag      | length |  string value |  comment |
| -------- | ------- | ----------------------- | -------------------------------------------|
| 9f26  | 10    | "e18d2a69a45dd09a" |  16 bytes 1 byte for each character | 
| 9f36 |  04     |  "0183"  |   value bytes : {0x30, 0x31, 0x38, 0x33}| 
| 9f37    | 08    |  "ab34b0bd" | |



the issue is related to The BERTLVAsciiHexPackager implementation of BERTLVPackager.  specifically   getUninterpretLength(int, binaryInterpeter).



I actually resolved the issue and submitted a [pull request](https://github.com/jpos/jPOS/pull/570).  


the issue was that getUninterpretLength always returned 0 when it should have return 0.5  . that is because it was performing Integer division.

**Comment by ar** [comment]
Got it. Please see my comments in #570, and if you agree with the solution (changing evaluation order) and works for you, we can merge it right away.
