### ISSUE TITLE
Channel Class that wraps the JMS objects

### ISSUE THREAD

**Issue by mehrdad2000** [jpos/jPOS#569]
Hi
Need to write Channel Class that wraps the JMS objects.

It would have to implement [ISOChannel](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/iso/ISOChannel.java) to be able to connect, send, receive etc. via JMS queue.

It should implement [Configurable](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/core/Configurable.java) so i can pass in required properties via the test plan.

Here is the scenario:

I try to send message from jmeter-iso8583 to mq, but it’s not work.

here is the my current JSR223 sampler that work correctly and send “mymessage“ to mq, now question is how can i send output of iso8583 plugin to mq server?
Is it possible to add “queue manager, channel, user, pass, queue name,…) in connection manager of jmeter-iso8583?

import com.ibm.jms.JMSTextMessage;
import com.ibm.mq.jms.*;
import com.ibm.msg.client.wmq.WMQConstants;

import javax.jms.JMSException;
import javax.jms.Session;

MQQueueConnectionFactory cf = new MQQueueConnectionFactory();
cf.setHostName("192.168.1.1");
cf.setPort(1443); // or other port
cf.setIntProperty(WMQConstants.WMQ_CONNECTION_MODE, WMQConstants.WMQ_CM_CLIENT);
cf.setQueueManager("qm");
cf.setChannel("my.SVRCONN");
cf.setStringProperty(WMQConstants.USERID, "user");
cf.setStringProperty(WMQConstants.PASSWORD, "pass");
connection = (MQQueueConnection) cf.createQueueConnection();
MQQueueSession session = (MQQueueSession) connection.createQueueSession(false, Session.AUTO_ACKNOWLEDGE);
MQQueue queue = (MQQueue) session.createQueue("queue:///my.queue");
MQQueueSender sender = (MQQueueSender) session.createSender(queue);
JMSTextMessage message = (JMSTextMessage) session.createTextMessage("mymessage");
connection.start();
sender.send(message);

Related issue:
https://github.com/tilln/jmeter-iso8583/issues/73

Any idea?
Thanks

**Comment by ar** [comment]
This is not a jPOS issue.
