### ISSUE TITLE
When two Q2 services are connected, the response content cannot be received.

### ISSUE THREAD

**Issue by MartinKayJr** [jpos/jPOS#574]
This is like this, we have two Q2 services. When we use A service to request B service, B service can receive data through process. When responding through ISOSource isoSource.send(isoRes);, the problem is sent, and A service cannot Any content received.

**Comment by ar** [comment]
This not a jPOS issue and not the right place to ask. Browse the [jPOS users mailing list](https://groups.google.com/g/jpos-users) and ask there. Search StackOverflow using the #jPOS tag for similar questions. See [Resources](http://jpos.org/resources) for further pointers.
